### ISSUE TITLE
Latest 3DSExplorer

### ISSUE THREAD

**Issue by ghost** [d0k3/3DS-Tools-Collection#2]
This 3DSExplorer looks 3DSGuy source addition of this patch https://github.com/Lectem/3dsexplorer/issues/9

I think Latest 3DSExplorer is modifications by Eli Sherer.
Update add more detailed CCI info, fix extract exefs and breaking 4GB rom un-trim.
Please check it.
https://github.com/bkifft/rom_tool/tree/master/3DSExplorer

**Comment by d0k3** [comment]
Yeah, I tried some variants. Have you tested this without problems and can you assure everything works fine while not breaking anything? If so, can you provide a compiled binary and maybe do a pull request?

**Comment by ghost** [comment]
I have tested again that works fine under Windows XP and 10.
so, I make a pull request. https://github.com/d0k3/3DS-Tools-Collection/pull/3

**Comment by d0k3** [comment]
Merged your pull request, thank you!
