### ISSUE TITLE
I get this error while running the .exe

### ISSUE THREAD

**Issue by Sonia-7** [d0k3/3DS-Tools-Collection#5]
![1](https://user-images.githubusercontent.com/24638400/34645768-468a12bc-f33d-11e7-9f38-4e73a36e9e6c.png)

![2](https://user-images.githubusercontent.com/24638400/34645775-71f54e80-f33d-11e7-904d-68dcfef66202.png)

If I press "Continue" the program still works fine. But what's causing this error, and how could I prevent it from happening?

**Comment by d0k3** [comment]
You should contact the 3DSExplorer author about this issue. As it stands, I'm only the maintainer of this (somewhat outdated, we need a new maintainer) collection of 3DS tools. Closing this now, as I can't do anything about this.
